#include "libTIM.h"

void PWM_Init_TIM4(){
	RCC->APB1ENR |= RCC_APB1ENR_TIM4EN;
	RCC->APB2ENR |= RCC_APB2ENR_IOPBEN;
	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;
}
void PWM_Init_TIM2(){
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
	RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;
	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;


}
void PWM_Servo_Init_TIM3(){
	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;
	RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;
	RCC->APB2ENR |= RCC_APB2ENR_IOPBEN;
	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;

	GPIOA->CRL &= ~GPIO_CRL_MODE6;
	GPIOA->CRL |= GPIO_CRL_MODE6;
	GPIOA->CRL &= ~GPIO_CRL_CNF6;
	GPIOA->CRL |= GPIO_CRL_CNF6_1;


	TIM3->CR1 &= ~TIM_CR1_CEN;
	TIM3->ARR = 2000;
	TIM3->PSC = 720 - 1;


	TIM3->CCMR1 |= TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1M_1;
	TIM3->CCER |= TIM_CCER_CC1E;
	TIM3->CCER &= ~TIM_CCER_CC1P;
	TIM3->CR1 &= ~TIM_CR1_DIR;
	TIM3->CR1 |= TIM_CR1_CEN;





}


void PWM_Level_TIM3_Ch1(uint16_t microsec){
	TIM3->CCR1 = microsec;
}
void PWM_Level_TIM3_Ch2(uint16_t microsec){
	TIM3->CCR2 = microsec;
}
void PWM_Level_TIM3_Ch3(uint16_t microsec){
	TIM3->CCR3 = microsec;
}
void PWM_Level_TIM3_Ch4(uint16_t microsec){
	TIM3->CCR4 = microsec;
}

void Encoder_Init_TIM4(){
	RCC->APB1ENR |= RCC_APB1ENR_TIM4EN;
	RCC->APB2ENR |= RCC_APB2ENR_IOPBEN;
	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;

	GPIOB->CRL &= ~GPIO_CRL_MODE6;	// mode 00 - input
	GPIOB->CRL |= GPIO_CRL_CNF6_1;	// input
	GPIOB->CRL &= ~GPIO_CRL_MODE7;	// mode 00 - input
	GPIOB->CRL |= GPIO_CRL_CNF7_1;	// input
	GPIOB->ODR |= GPIO_ODR_ODR6;	// pull up
	GPIOB->ODR |= GPIO_ODR_ODR7;	// pull up

	TIM4->CCMR1 |= TIM_CCMR1_IC1F | TIM_CCMR1_IC2F;
	TIM4->CCMR1 &= ~(TIM_CCMR1_CC1S | TIM_CCMR1_CC2S);
	TIM4->CCMR1 |= TIM_CCMR1_CC1S_0 | TIM_CCMR1_CC2S_0;

	TIM4->CCER &= ~(TIM_CCER_CC1P | TIM_CCER_CC2P);

	TIM4->SMCR |= TIM_SMCR_SMS_0 |  TIM_SMCR_SMS_1 ; // 011  Encoder Mode 3


	TIM4->ARR = 100;
	TIM4->CR1 |= TIM_CR1_CEN;

	TIM4->CNT = 0;



}

void PWM_Power_Init_TIM3(){
		RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;
		RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;
		RCC->APB2ENR |= RCC_APB2ENR_IOPBEN;
		RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;


		GPIOA->CRL &= ~GPIO_CRL_MODE7;   //  PA7
		GPIOA->CRL |= GPIO_CRL_MODE7;
		GPIOA->CRL &= ~GPIO_CRL_CNF7;
		GPIOA->CRL |= GPIO_CRL_CNF7_1;


		TIM3->CR1 &= ~TIM_CR1_CEN;

		TIM3->ARR = 2000;
		TIM3->PSC = 720 - 1;

		TIM3->CCMR1 |= TIM_CCMR1_OC2M_2 | TIM_CCMR1_OC2M_1;
		TIM3->CCER |= TIM_CCER_CC2E;
		TIM3->CCER &= ~TIM_CCER_CC2P;
		TIM3->CR1 &= ~TIM_CR1_DIR;
		TIM3->CR1 |= TIM_CR1_CEN;
}





